name: Log4jInjectionFilter
version: '${project.version}'
main: not.hub.log4jinjectionfilter.Plugin
api-version: 1.18
authors: [ nothub ]
description: Filter log4j exploit attempts
website: https://github.com/nothub/Log4jInjectionFilter
