name: 🧑‍🏭

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: true

      - name: Package
        run: mvn --batch-mode --show-version --errors package --file pom.xml

      - name: Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'automated release at commit ${{ github.sha }}'
          draft: false
          prerelease: false

      - name: Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "target/Log4jInjectionFilter-*.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
